[package]
name = "shared-bus"
version = "0.1.5"
authors = ["Rahix <rahix@rahix.de>"]

description = "Abstraction for sharing a bus between multiple devices."
homepage = "https://github.com/Rahix/shared-bus"
repository = "https://github.com/Rahix/shared-bus"
documentation = "https://docs.rs/shared-bus"
readme = "README.md"
keywords = ["embedded-hal", "embedded-hal-impl", "i2c", "spi", "bus"]
categories = ["embedded", "no-std"]
license = "MIT/Apache-2.0"

[dependencies]
embedded-hal = "0.2.1"

[dev-dependencies]
embedded-hal-mock = "0.4.0"

[dependencies.cortex-m]
optional = true
version = "0.5.4"

[dependencies.riscv]
optional = true
version = "0.5.2"

[features]
std = []
docsrs = []
cortexm = ["cortex-m"]
risc-v = ["riscv"]

[package.metadata.docs.rs]
all-features = true
